export const FETCH_SHOP_ITEMS = 'FETCH_SHOP_ITEMS'

export const FETCH_TIMETABLE = 'FETCH_TIMETABLE'
export const FETCH_SPECIAL_COURSES = 'FETCH_SPECIAL_COURSES'
export const FETCH_SPECIAL_COURSES_BANNER = 'FETCH_SPECIAL_COURSE_BANNER'

export const ADD_TO_CART_AND_CHECKOUT = 'ADD_TO_CART_AND_CHECKOUT'

export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const AUTH_ERROR = 'AUTH_ERROR'

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'

export const FETCH_PLACE_INFO = 'FETCH_PLACE_INFO'

export const FETCH_INSTRUCTOR_INFO = 'FETCH_INSTRUCTOR_INFO'
