export const FETCH_SHOP_ITEMS = 'FETCH_SHOP_ITEMS'

export const FETCH_TIMETABLE = 'FETCH_TIMETABLE'
export const FETCH_SPECIAL_COURSES = 'FETCH_SPECIAL_COURSES'
export const FETCH_SPECIAL_COURSES_BANNER = 'FETCH_SPECIAL_COURSE_BANNER'

export const ADD_TO_CART_AND_CHECKOUT = 'ADD_TO_CART_AND_CHECKOUT'

export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const AUTH_ERROR = 'AUTH_ERROR'

export const USER_DETAILS_UPDATED_IN_DB = 'USER_DETAILS_UPDATED_IN_DB'
export const STOP_UPDATING_USER_DETAILS_FROM_DB = 'STOP_UPDATING_USER_DETAILS_FROM_DB'
export const USER_ERROR = 'USER_ERROR'
export const UPDATE_USERS_TRANSACTIONS = 'UPDATE_USERS_TRANSACTIONS'
export const UPDATE_USERS_BOOKINGS = 'UPDATE_USERS_BOOKINGS'

export const FETCH_PLACE_INFO = 'FETCH_PLACE_INFO'

export const FETCH_INSTRUCTOR_INFO = 'FETCH_INSTRUCTOR_INFO'

export const PUT_COURSE_INFO = 'PUT_COURSE_INFO'
export const FETCH_COURSE_BOOKINGS = 'FETCH_COURSE_BOOKINGS'
export const REMOVE_COURSE_INFO = 'REMOVE_COURSE_INFO'

export const FETCH_USER_LIST = 'FETCH_USER_LIST'
export const FETCH_ADMIN_LIST = 'FETCH_ADMIN_LIST'
export const EXPAND_ADMIN_LIST = 'EXPAND_ADMIN_LIST'
export const MINIMIZE_ADMIN_LIST = 'MINIMIZE_ADMIN_LIST'
export const EXPAND_USER_LIST = 'EXPAND_USER_LIST'
export const MINIMIZE_USER_LIST = 'MINIMIZE_USER_LIST'
